### ISSUE TITLE
How is this build?

### ISSUE THREAD

**Issue by pepa65** [notjedi/localsend-rs#1]
After cloning the repo I tried `cargo build` but that didn't work. Do I need to install https://github.com/programatik29/axum-server first?

**Comment by notjedi** [comment]
nope, you need to apply a patch file. please do a `git pull` and apply the `tls-hostname.patch` using the command `git apply tls-hostname.patch` and if you are curious to know why this patch is required, please take a look at the links provided in the https://github.com/notjedi/localsend-rs/blob/main/sni.md file

**Comment by pepa65** [comment]
Thanks, seems to work!
Feedback on the patch: `git apply tls-hostname.patch`:
```
tls-hostname.patch:1057: new blank line at EOF.
+
warning: 1 line adds whitespace errors.
```
